### ISSUE TITLE
std::is_trivially_default_constructible in include/ceres/internal/fixed_array.h#L89 is not support for gcc4.9(c++11)

### ISSUE THREAD

**Issue by ArmstrongYang** [ceres-solver/ceres-solver#472]
Hello, I find a bug for compiler gcc4.9(c++11), because the following function is not support in 
https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/internal/fixed_array.h#L89
```c++
static constexpr bool DefaultConstructorIsNonTrivial() {
    return !std::is_trivially_default_constructible<StorageElement>::value;
  }
```

you can reproduce this error in cppreference.com:

**https://en.cppreference.com/w/cpp/types/is_default_constructible**

change compiler to gcc4.9(c++11)

![image](https://user-images.githubusercontent.com/13563376/56114143-8c95c400-5f92-11e9-96ec-e8f76a2045f3.png)

https://coliru.stacked-crooked.com/view?id=4880129794bb9370

```
main.cpp: In function 'int main()':
main.cpp:16:18: error: 'is_trivially_default_constructible' is not a member of 'std'
               << std::is_trivially_default_constructible<Ex1>::value << '\n'
                  ^
main.cpp:16:61: error: expected primary-expression before '>' token
               << std::is_trivially_default_constructible<Ex1>::value << '\n'
                                                             ^
main.cpp:16:62: error: '::value' has not been declared
               << std::is_trivially_default_constructible<Ex1>::value << '\n'
                                                              ^
main.cpp:18:18: error: 'is_trivially_default_constructible' is not a member of 'std'
               << std::is_trivially_default_constructible<Ex2>::value << '\n'
                  ^
main.cpp:18:61: error: expected primary-expression before '>' token
               << std::is_trivially_default_constructible<Ex2>::value << '\n'
                                                             ^
main.cpp:18:62: error: '::value' has not been declared
               << std::is_trivially_default_constructible<Ex2>::value << '\n'
                                                              ^
```
Hope you could fix this!

**Comment by sandwichmaker** [comment]
@JohannesBeck PTAL.

**Comment by JohannesBeck** [comment]
The problem is, that gcc4.9 does not have full c++11 support and I think this gcc version is not support by ceres. At least gcc5 is needed. The function DefaultConstructorIsNonTrivial could be changed to compile with gcc4.9 but there are other problems when using that compiler (see e.g. issue #291).
Would it be possible for you to change the gcc compiler to a more recent one?

**Comment by sandwichmaker** [comment]
Yes with the current development version of ceres,  you need a c++11 compliant toolchain.

**Comment by sandwichmaker** [comment]
Closing as this version of the compiler is too old.

**Comment by ArmstrongYang** [comment]
> The problem is, that gcc4.9 does not have full c++11 support and I think this gcc version is not support by ceres. At least gcc5 is needed. The function DefaultConstructorIsNonTrivial could be changed to compile with gcc4.9 but there are other problems when using that compiler (see e.g. issue #291).
> Would it be possible for you to change the gcc compiler to a more recent one?

Thank you very much. I fix this by reverting to latest publish version 1.14.0.
