### ISSUE TITLE
Unable to build tests on Ubuntu with gcc

### ISSUE THREAD

**Issue by seanbow** [ceres-solver/ceres-solver#437]
I'm trying to compile Ceres with:
  - Ubuntu 16.04
  - Eigen 3.3.90
  - gcc 5.5 and gcc 7.3 (same error on both)

When compiling the test `residual_block_test.cc`, I get the following error:

```
In file included from /home/sean/code/ceres-solver/internal/ceres/residual_block_test.cc:34:0:
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h: In instantiation of ‘void testing::internal::DefaultPrintTo(testing::internal::IsContainer, testing::internal::false_type, const C&, std::ostream*) [with C = Eigen::Matrix<double, -1, -1, 1>; testing::internal::IsContainer = int; testing::internal::false_type = testing::internal::bool_constant<false>; std::ostream = std::basic_ostream<char>]’:
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:10546:17:   required from ‘void testing::internal::PrintTo(const T&, std::ostream*) [with T = Eigen::Matrix<double, -1, -1, 1>; std::ostream = std::basic_ostream<char>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:10776:12:   required from ‘static void testing::internal::UniversalPrinter<T>::Print(const T&, std::ostream*) [with T = Eigen::Matrix<double, -1, -1, 1>; std::ostream = std::basic_ostream<char>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:10925:30:   required from ‘void testing::internal::UniversalPrint(const T&, std::ostream*) [with T = Eigen::Matrix<double, -1, -1, 1>; std::ostream = std::basic_ostream<char>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:10853:19:   required from ‘static void testing::internal::UniversalTersePrinter<T>::Print(const T&, std::ostream*) [with T = Eigen::Matrix<double, -1, -1, 1>; std::ostream = std::basic_ostream<char>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:11051:44:   required from ‘std::__cxx11::string testing::PrintToString(const T&) [with T = Eigen::Matrix<double, -1, -1, 1>; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:10345:36:   required from ‘static std::__cxx11::string testing::internal::FormatForComparison<ToPrint, OtherOperand>::Format(const ToPrint&) [with ToPrint = Eigen::Matrix<double, -1, -1, 1>; OtherOperand = Eigen::Matrix<double, -1, -1, 1>; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:10420:45:   required from ‘std::__cxx11::string testing::internal::FormatForComparisonFailureMessage(const T1&, const T2&) [with T1 = Eigen::Matrix<double, -1, -1, 1>; T2 = Eigen::Matrix<double, -1, -1, 1>; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:19989:53:   required from ‘testing::AssertionResult testing::internal::CmpHelperEQFailure(const char*, const char*, const T1&, const T2&) [with T1 = Eigen::Matrix<double, -1, -1, 1>; T2 = Eigen::Matrix<double, -1, -1, 1>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:20006:28:   required from ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = Eigen::Matrix<double, -1, -1, 1>; T2 = Eigen::Matrix<double, -1, -1, 1>]’
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:20030:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = Eigen::Matrix<double, -1, -1, 1>; T2 = Eigen::Matrix<double, -1, -1, 1>; bool lhs_is_null_literal = false]’
/home/sean/code/ceres-solver/internal/ceres/residual_block_test.cc:298:3:   required from here
/home/sean/code/ceres-solver/internal/ceres/gtest/gtest.h:10445:35: error: variable or field ‘it’ declared void
   for (typename C::const_iterator it = container.begin();
```

Somehow `IsContainerTest<Eigen::MatrixXd>` is resolving to true, I guess.

**Comment by jcarpent** [comment]
Hi @seanbow,
Just for your information, you are currently working with the latest development version of Eigen (3.3.90), where some types have still an incomplete definition, and so on. 
Certainly working with EIgen 3.3.5 will avoid you some debugging.

**Comment by maShimizu** [comment]
I also same problem.
I use Eigen 3.3~beta1-2 by apt-get install
Should I install Eigen 3.3.5 from source code?

**Comment by jcarpent** [comment]
@maShimizu On which Ubuntu distribution? 16.04?

**Comment by sandwichmaker** [comment]
yeah this looks like a recent change to eigen at head. I am going to close this as this is an eigen version issue rather than a ceres issue.

**Comment by maOpera** [comment]
Thank you for your Kindly reply.
I'll install Eigen 3.3.5 or before version from source code.

**Comment by vlv-squid** [comment]
Set option(BUILD_TESTING "Enable tests" OFF) in 'CMakeLists.txt' works for me.
