### ISSUE TITLE
Build fails: SuiteSparseQR.hpp: No such file or directory

### ISSUE THREAD

**Issue by luator** [ceres-solver/ceres-solver#400]
After pulling updates from master, the build is failing for me (using Ubuntu 16.04) with the following error:

    ceres-solver/internal/ceres/suitesparse.h:44:29: fatal error: SuiteSparseQR.hpp: No such file or directory

The missing file is installed on my machine with this path: `/usr/include/suitesparse/SuiteSparseQR.hpp`

I think it is caused by 2166bad133d279ec28008f1df8b4d90a7023f531 as this is the first commit that is failing for me. I am happy to provide more information if needed.

**Comment by alexsmac** [comment]
I can't replicate this on an Ubuntu machine with the same installation paths for SuiteSparse.  Is this starting from a completely clean build directory?  Also what build is failing - Ceres itself, or something dependent upon Ceres?

**Comment by luator** [comment]
It is ceres itself. I can produce the error with an isolated, clean build like this:
```
git clone git@github.com:ceres-solver/ceres-solver.git
cd ceres-solver
mkdir build
cd build
cmake ..
make -j8
```

For a bit more context, this is the full error I get:
```
In file included from /home/fwidmaier/ceres-foo/ceres-solver/internal/ceres/covariance_impl.h:41:0,
                 from /home/fwidmaier/ceres-foo/ceres-solver/internal/ceres/covariance_test.cc:41:
/home/fwidmaier/ceres-foo/ceres-solver/internal/ceres/suitesparse.h:44:29: fatal error: SuiteSparseQR.hpp: No such file or directory
compilation terminated.
internal/ceres/CMakeFiles/covariance_test.dir/build.make:62: recipe for target 'internal/ceres/CMakeFiles/covariance_test.dir/covariance_test.cc.o' failed
make[2]: *** [internal/ceres/CMakeFiles/covariance_test.dir/covariance_test.cc.o] Error 1
CMakeFiles/Makefile2:3096: recipe for target 'internal/ceres/CMakeFiles/covariance_test.dir/all' failed
make[1]: *** [internal/ceres/CMakeFiles/covariance_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by alexsmac** [comment]
OK - I can replicate this when using a standard environment rather than my dev environment, it should be fixed by [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/13820), please can you confirm that this fixes the problem for you.

**Comment by alexsmac** [comment]
The CL has now been merged into master, please re-open the issue if the problem still remains (it fixes the issue when I was able to replicate it).

**Comment by luator** [comment]
It is good now, thanks a lot for fixing this so fast!

**Comment by psychochair** [comment]
Hello @alexsmac, I have the same issue when I try to build ceres on a Ubuntu docker image. Here is the sequence of the install in the Dockerfile:

`    # install ceres
RUN apt-get install libgoogle-glog-dev libgflags-dev -y && \
    apt-get install libatlas-base-dev -y && \
    apt-get install libsuitesparse-dev -y && \
    git clone https://github.com/ceres-solver/ceres-solver && \
    cd ceres-solver && mkdir build && cd build && \
    cmake .. && \
    make -j$(nproc) && \
    make install`

and here is the error

`/[//]/ceres-solver/internal/ceres/suitesparse.h:46:10: fatal error: SuiteSparseQR.hpp: No such file or directory
   46 | #include "SuiteSparseQR.hpp"`

Is this related?
