### ISSUE TITLE
Examples fail to build on i386 with -DCXX11=on

### ISSUE THREAD

**Issue by jbeich** [ceres-solver/ceres-solver#235]
https://github.com/freebsd/freebsd/commit/b71b1dcf10941dcc438f95f3cd8e2e7f6acd5fb0 may (or not) be related.

```
$ c++ -v
FreeBSD clang version 3.8.0 (tags/RELEASE_380/final 262564) (based on LLVM 3.8.0)
Target: i386-unknown-freebsd11.0
Thread model: posix
InstalledDir: /usr/bin

$ pkg info -x eigen
eigen-3.2.10
```

```c++
In file included from examples/helloworld.cc:36:
In file included from include/ceres/ceres.h:37:
In file included from include/ceres/autodiff_cost_function.h:132:
In file included from include/ceres/internal/autodiff.h:145:
include/ceres/jet.h:246:3: error: requested alignment is less than minimum alignment of 4 for type 'Eigen::Matrix<double, 1, 1, kAlignHint>'
  alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignHint> v;
  ^
include/ceres/internal/autodiff.h:232:34: note: in instantiation of template class 'ceres::Jet<double, 1>' requested here
    FixedArray<JetT, (256 * 7) / sizeof(JetT)> x(
                                 ^
include/ceres/autodiff_cost_function.h:211:53: note: in instantiation of member function 'ceres::internal::AutoDiff<CostFunctor, double, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0>::Differentiate' requested here
           N0, N1, N2, N3, N4, N5, N6, N7, N8, N9>::Differentiate(
                                                    ^
examples/helloworld.cc:70:11: note: in instantiation of member function 'ceres::AutoDiffCostFunction<CostFunctor, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0>::Evaluate' requested here
      new AutoDiffCostFunction<CostFunctor, 1, 1>(new CostFunctor);
          ^
```

**Comment by alexsmac** [comment]
@jbeich - please can you try this CL: https://ceres-solver-review.googlesource.com/#/c/9100/ - hopefully it should fix your problem.

**Comment by jbeich** [comment]
I confirm. Applying CL 9100 patch fixes the issue. Tested on Clang 3.8 and 3.4.1.

**Comment by alexsmac** [comment]
Great thanks, I'm going to merge it into master now.

**Comment by jbeich** [comment]
Ironically, after b4e2724 GCC is now failing. FreeBSD defaults to Clang but I'm using ([via port](http://freshports.org/math/ceres-solver)) GCC by default for OpenMP support. libomp.so from LLVM doesn't work on FreeBSD i386 yet.

```c++
In file included from include/ceres/internal/variadic_evaluate.h:37:0,
                 from include/ceres/internal/numeric_diff.h:45,
                 from include/ceres/dynamic_numeric_diff_cost_function.h:44,
                 from include/ceres/gradient_checker.h:41,
                 from internal/ceres/gradient_checker.cc:33:
include/ceres/jet.h:250:58: error: requested alignment is not a positive power of 2
   alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignHint> v;
                                                          ^
```

**Comment by alexsmac** [comment]
Interesting.  That's also actually against the standard I think, alignas(0) should always be ignored.  OK, I will create another patch now.

**Comment by alexsmac** [comment]
@jbeich please try this: https://ceres-solver-review.googlesource.com/9104

**Comment by alexsmac** [comment]
Actually I checked on a GCC machine I have available, it's still broken.

**Comment by alexsmac** [comment]
OK - please try again now.

**Comment by jbeich** [comment]
Builds fine with both Clang 3.4/3.8 and GCC 4.8.

**Comment by alexsmac** [comment]
Thanks - the second fix is now merged into master.
