### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by gogogoKKK** [ceres-solver/ceres-solver#495]
The commit is 3e5db5bc. 
```
/home/aaa/ceres-solver/internal/ceres/fixed_array_test.cc:123:25:   required from here
/usr/include/eigen3/Eigen/src/Core/util/Memory.h:731:9: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = int; _Dp = std::default_delete<int>]’
         ::new( p ) T( value );
         ^
In file included from /usr/include/c++/5/memory:81:0,
                 from /home/aaa/ceres-solver/include/ceres/internal/fixed_array.h:36,
                 from /home/aaa/ceres-solver/internal/ceres/fixed_array_test.cc:15:
```
A stable version can be used in my environment.

**Comment by alexsmac** [comment]
What OS and compiler are you using?

**Comment by gogogoKKK** [comment]
@alexsmac I compile the code on ubuntu 16.04 and gcc 5.4.0 is used.

**Comment by alexsmac** [comment]
Our Travis CI system builds for 16.04 using GCC 5.4 and passes without errors on master (and didn't fail for that commit) see [here](https://travis-ci.org/ceres-solver/ceres-solver/jobs/563792232) for the latest GCC build using Eigen 3.3.4, what version are you using ?

**Comment by gogogoKKK** [comment]
@alexsmac I am using Eigen 3.2.5

**Comment by alexsmac** [comment]
That's a very old version of Eigen, and not the default libeigen3-dev package version on 16.04.  The problem appears to be the aligned allocator within Eigen in 3.2.5 (which is used by FixedArray) is not movable.  I would either update your Eigen package to a newer version, or try using the last 1.14 release of Ceres.

**Comment by gogogoKKK** [comment]
@alexsmac Thanks a lot.
