### ISSUE TITLE
What version of SuiteSparse is compatible with ceres?

### ISSUE THREAD

**Issue by jasjuang** [ceres-solver/ceres-solver#297]
Could you let me know what version of SuiteSparse is expected to be compatible with the current ceres?

I am trying to coordinate with [vcpkg](https://github.com/Microsoft/vcpkg/) to get ceres easily installed on Windows by simply doing `vcpkg install ceres`. The current state is SuiteSparse 4.5.5 compiles with the old ceres 1.12.0 release without a problem, but we need the up-to-date cmake commits. If I try to compile the head ceres with SuiteSparse 4.5.5, I get the below compilation error:

``````
            Creating library C:/dev/vcpkg/buildtrees/ceres/x64-windows-rel/lib/Release/ceres.lib and object C:/dev/vcpkg/buildtrees/ceres/x64-windows-rel/lib/Release/ceres.exp
     4>libcholmod.lib(cholmod_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_recommended referenced in function cholmod_ccolamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_set_defaults referenced in function ccolamd_interface [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_csymamd.o.obj) : error LNK2001: unresolved external symbol ccolamd_set_defaults [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd referenced in function ccolamd_interface [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_csymamd.o.obj) : error LNK2019: unresolved external symbol csymamd referenced in function cholmod_csymamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_l_recommended referenced in function cholmod_l_ccolamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_l_set_defaults referenced in function ccolamd_interface [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_csymamd.o.obj) : error LNK2001: unresolved external symbol ccolamd_l_set_defaults [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_l referenced in function ccolamd_interface [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>libcholmod.lib(cholmod_l_csymamd.o.obj) : error LNK2019: unresolved external symbol csymamd_l referenced in function cholmod_l_csymamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\bin\Release\ceres.dll : fatal error LNK1120: 8 unresolved externals [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]
     4>Done Building Project "C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj" (default targets) -- FAILED.
     3>Done Building Project "C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\ALL_BUILD.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\install.vcxproj" (default targets) -- FAILED.

Build FAILED.
``````

Based on the compilation error could you provide us some insights? Is SuiteSparse 4.5.5 expected to compile with the head ceres or a newer SuiteSparse is required?

**Comment by sandwichmaker** [comment]
This looks like a linking problem not a problem with ceres. you are not linking to ccolamd.

**Comment by jasjuang** [comment]
@sandwichmaker Hard for me to imagine there is something wrong with the linking because the exact same configuration works for ceres 1.12.0. I am guessing it linked but the latest ceres might be using a newer api of Suitesparse but 4.5.5 is too old hence the unresolved external symbol. I know that you guys don't work on Windows, but in linux, what version of SuiteSparse is required for the latest ceres?

**Comment by sandwichmaker** [comment]
4.5.4 is what I use on my mac using homebrew.

**Comment by sandwichmaker** [comment]
@jasjuang notice the functions that are complaining, 

     4>libcholmod.lib(cholmod_ccolamd.o.obj) : error LNK2019: unresolved external symbol ccolamd_recommended referenced in function cholmod_ccolamd [C:\dev\vcpkg\buildtrees\ceres\x64-windows-rel\internal\ceres\ceres.vcxproj]

cholmod_ccolamd is complaining that it cannot find ccolamd_recommended. 

CHOLMOD provides wrappers to various other parts of SuiteSparse so in this case cholmod_ccolamd which is the interface to CCOLAMD is unable to find ccolamd_recommended.

**Comment by jasjuang** [comment]
@sandwichmaker Thanks for the info. I downgraded SuiteSparse to 4.5.4 but I still encounter the same compilation error. I am still trying to figure out whether something has to be changed on SuiteSparse or Ceres to fix this. When I build SuiteSparse, libccolamd.lib, libcholmod.lib and libcolamd.lib are generated. Should I be expecting a llibccolamd_recommended.lib? But again the old 1.12.0 ceres release compiles without a problem with the current setup for SuiteSparse, which means something changed in Ceres causing it to not compile. I am currently stuck at the moment, please let me know if you have any more ideas.

**Comment by sandwichmaker** [comment]
Can you try bisecting from 1.12.0 and the head to see what commit
introduced this problem?

**Comment by sandwichmaker** [comment]
so this seems like a windows problem, because on the mac everything builds fine.

**Comment by jasjuang** [comment]
@sandwichmaker I am having difficulties to build suitesparse from source on windows, and for some reason if I build ceres from source it won't recognize the suitesparse from vcpkg. The only way I get ceres to work with suitesparse is build them both from vcpkg, but I am not able to find a way to checkout particular commit to build on vcpkg, the only option I have is either the stable releases or the latest on HEAD. I am working with the people at vcpkg to figure this out. I will keep you updated.

**Comment by jasjuang** [comment]
@sandwichmaker I just figured out which commit breaks it. It's fa39fae. I was able to compile commit ec5bd23. My guess is some change in FindSuiteSparse.cmake breaks it. Could you provide some insights on what change in FindSuiteSparse.cmake could potentially break it?

**Comment by sandwichmaker** [comment]
aha there is a bug in there. hold tight I have a fix.

**Comment by sandwichmaker** [comment]
can you try https://ceres-solver-review.googlesource.com/#/c/10680/ 
to see if it fixes your problem. It is a one character fix.

**Comment by jasjuang** [comment]
Just finished rebuilding and it compiles! Can you also make a release after this commit?

**Comment by sandwichmaker** [comment]
Committed to head. So you should be able to use it. As for a release, I am in the midst of landing another large change to line search minimizer and perhaps one more feature before I do a release candidate for 1.13.0.
